In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import scipy as sp
import ast
from mpl_toolkits.mplot3d import Axes3D
import edenutil

%matplotlib inline
%load_ext autoreload
%autoreload 2

try:
   import cPickle as pickle
except:
   import pickle

def save_obj(obj, name ):
    with open('../data/'+ name + '.pkl', 'wb') as f:
        pickle.dump(obj, f, pickle.HIGHEST_PROTOCOL)

def load_obj(name):
    with open(name, 'rb') as f:
        return pickle.load(f)

In [2]:
dir_ = 'io/cluster_data/'
model_gac_t = load_obj(dir_+'cluster_data_fn_1,12,2,20,21,23,28,29,30,33,35,40,5,6_method_ltc_algo_gactemporal_params_{"p": 0.7, "s": 0.7}.p')
model_kmeans = load_obj(dir_+'cluster_data_fn_1,12,2,20,21,23,28,29,30,33,35,40,5,6_method_ltc_algo_kmeans_params_{"n_clusters": 150}.p')
data_pre = load_obj('io/preprocess_data/preprocess_data_fn_1,12,2,20,21,23,28,29,30,33,35,40,5,6_method_ltc.p')

In [3]:
ids_ = data_pre['id'].values
ec_gac_t = edenutil.match_event_cluster(edenutil.get_df_label(ids_, model_gac_t), edenutil.get_df_eval('1,12,2,20,21,23,28,29,30,33,35,40,5,6'))
vsm_re = edenutil.recon_vsm(data_pre['vsm'])

1
12
2
20
21
23
28
29
30
33
35
40
5
6


In [4]:
ec_gac_t

{1: (519.0, 13),
 2: (1148.0, 7),
 5: (1306.0, 39),
 6: (543.0, 7),
 13: (289.0, 19),
 22: (341.0, 9),
 23: (1344.0, 25),
 27: (1089.0, 18),
 33: (1056.0, 3),
 34: (663.0, 3),
 35: (1069.0, 17),
 39: (813.0, 7),
 41: (744.0, 6),
 46: (737.0, 7)}

In [5]:
data_pre['cluster'] = model_gac_t.labels_

In [55]:
for name, group in data_pre.groupby('cluster'):
    if name in [i[0] for i in ec_gac_t.values()]:
        print "***"
        print name
#         print 'cluster found'
        group_vsm = edenutil.recon_vsm(group['vsm'])
        centroid = group_vsm.mean(axis=0)
        top_indices = centroid.argsort()[::-1][:15]
        sim = []
        for v in group['vsm'].values:
            sim.append(edenutil.mycosine(v, centroid))
        print [vocab[term] for term in top_indices]
#         print sim
        top_articles = np.array(sim).argsort()[::-1][:3]
        titles = group['title'].values
        print [titles[articles] for articles in top_articles]

***
289.0
[u'alitalia', u'cassano', u'airlin', u'etihad', u'silvano', u'carrier', u'fiumicino', u'resign', u'rome', u'italian', u'montezemolo', u'reason', u'ceo', u'restructur', u'said']
[u'Alitalia board will seek right candidate for CEO - Hogan', u"Alitalia chief's move puts job up for grabs", u'Cassano quits as Alitalia CEO (2)']
***
341.0
[u'pesticid', u'potato', u'treat', u'rodenticid', u'crop', u'arabl', u'fungicid', u'encount', u'weight', u'survey', u'fruit', u'anticoagul', u'ware', u'2012', u'scotland']
[u'Little sign of an organic revolution in Scotland', u'Pesticide Usage in Scotland: Arable Crops and Potato Stores 2014', u'Pesticide Usage in Scotland']
***
519.0
[u'dunnhumbi', u'tesco', u'clubcard', u'wpp', u'sale', u'bidder', u'2bn', u'lewi', u'supermarket', u'dave', u'data', u'700m', u'loyalti', u'abandon', u'sunday']
[u'Tesco to sell Euro stores for \xa33bn', u"Tesco 'close to ditching Dunnhumby sale plans'", u'Tesco to keep hold of Dunnhumby data unit']
***
543.0
[u'shil

In [37]:
print type(centroid)

<type 'numpy.ndarray'>


In [12]:
group_vsm.shape

(29, 35101)

In [13]:
np.mean(group_vsm)

0.00033127803363663358

(35101,)

In [19]:
print type(model_kmeans.cluster_centers_)

<type 'numpy.ndarray'>


In [22]:
model_kmeans.cluster_centers_[0].argsort()[::-1]

array([22396, 30627,  9533, ...,  9234, 31022, 10796])

In [28]:
vect = edenutil.TfidfVectorizer(use_idf=True, norm='l2', sublinear_tf=True)
vsm = vect.fit_transform(data_pre['content_prepro'].values)

In [30]:
vocab = vect.get_feature_names()

In [46]:
group['vsm'].values

array([array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.]),
       array([ 0.,  0.,  0., ...,  0.,  0.,  0.])], dtype=object)

In [64]:
for name, group in data_pre.groupby('cluster'):
    if name == 519.0:
        print "***"
        print name
        print len(group)
#         print 'cluster found'
        group_vsm = edenutil.recon_vsm(group['vsm'])
        centroid = group_vsm.mean(axis=0)
        top_indices = centroid.argsort()[::-1][:15]
        sim = []
        for v in group['vsm'].values:
            sim.append(edenutil.mycosine(v, centroid))
        print [vocab[term] for term in top_indices]
#         print sim
        top_articles = np.array(sim).argsort()[::-1]
        titles = group['title'].values
        print [titles[articles] for articles in top_articles]
        
        incorrect = 0
        for id_ in group['id'].values:
            if not id_ in df_eval['story'].values:
                print "found mismatch"
                print id_

***
519.0
14
[u'dunnhumbi', u'tesco', u'clubcard', u'wpp', u'sale', u'bidder', u'2bn', u'lewi', u'supermarket', u'dave', u'data', u'700m', u'loyalti', u'abandon', u'sunday']
[u'Tesco to sell Euro stores for \xa33bn', u"Tesco 'close to ditching Dunnhumby sale plans'", u'Tesco to keep hold of Dunnhumby data unit', u'Tesco Close To Pulling \xa3700m Data Unit Sale', u'Official: Tesco Scraps dunnhumby Sale Plans', u'Tesco close to abandoning Dunnhumby sale', u'Clubcard deal flops as Tesco eyes Poland exit', u'Tesco Dunnhumby sale on verge of collapse', u'Tesco could scrap Dunnhumby sale - reports', u'Tesco abandons Dunnhumby sale after offers drop from \xa32bn to \xa3700m', u'Tesco may call off dunnhumby sale', u"Sale of Tesco's Clubcard business to WPP on the verge of collapse", u'Official: Tesco Scraps dunnhumby Sale Plans', u'Tesco Dunnhumby sale stalls but eastern European stores could fetch \xa33bn']
found mismatch
b7980e7c-cf1d-4433-8fa3-7455bc0c47d2


In [59]:
df_eval = edenutil.get_df_eval('1')

1


In [60]:
df_eval.head()

story  event decision
0  48f1fcb7-24af-4152-92ce-a2f2b7a72e59      1      YES
1  701c10d3-cac7-4bff-aa34-a821cbd4301a      1      YES
2  34d5dda9-c4d8-447d-b984-c8b166f6ef0e      1      YES
3  468e9c4e-86f8-4517-9c13-d480fbc19325      1      YES
4  75b924e0-fa25-47ba-a41c-7e793dc7d0b2      1      YES

In [68]:
incorrect_article = data_pre[data_pre['id'] == 'b7980e7c-cf1d-4433-8fa3-7455bc0c47d2']

In [70]:
print incorrect_article.title

1254    Tesco to sell Euro stores for £3bn
Name: title, dtype: object
